vagrant/apptest2/config/routes.rb
Rails.application.routes.draw do
 devise_for :users

 root to: "home#index"

 get  "home/about"  => "home#about"

 resources :books
 resources :users, only: [:show, :edit, :update, :index]
end

vagrant/apptest2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

vagrant/apptest2/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
    validates :body, presence: true, length: { maximum: 200 }

end

vagrant/apptest2/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  attachment :profile_image

  validates :name, presence: true, length: {minimum: 2, maximum: 20}
  validates :introduction, length: { maximum: 50 }
end

vagrant/apptest2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id) # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

vagrant/apptest2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book_user.id = current_user.id
    @book.save
    redirect_to books_path,notice: "You have creatad book successfully."
    end

  def index
    @book_path = Book.all.order(created_at: :desc)
    @teruya = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @book_path = Book.all.order(created_at: :desc)
    @teruya = User.find(current_user.id)
    @book = Book.new(book_params)
  end

  def edit
    @book = Book.find_by(params[:id])
  end

  def update
     @book =Book.find(params[:id])
     if @book.update(book_params)
     redirect_to book_path(@book), notice:"You have updated book successfully."
     else
      render :edit
    end
  end

  def destroy
    book = Book.find_by(params[:id])
    book.destroy
    redirect_to user_path(book.user), notice: "You have destroyed book successfully."
  end

  private

    def book_params
        params.require(:book).permit(:title, :body, :user_id)
    end
end

vagrant/apptest2/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

vagrant/apptest2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @teruya = User.find(current_user.id)
  	@user_path = User.all.order(created_at: :desc)
    @book = Book.new
  end

  # マイページ
  def show
  	@user = User.find(params[:id])
    @teruya = User.find(current_user.id)
  end

  def edit
  	@user = User.find_by(params[:id])
    redirect_to user_path(current_user)
  end

  def update
  	@user = User.find(params[:id])
    if @user.update(current_user_params)
      redirect_to @user, notice: "You have updated user information successfully"
    else
      render :edit
    end
  end

   private

    def user_params
      params.require(:user).permit(:name, :introduction, :profile_image)
    end
end

vagrant/apptest2/app/helpers/application_helper.rb
module ApplicationHelper
end

vagrant/apptest2/app/helpers/books_helper.rb
module BooksHelper
end

vagrant/apptest2/app/helpers/home_helper.rb
module HomeHelper
end

vagrant/apptest2/app/helpers/users_helper.rb
module UsersHelper
end

vagrant/apptest2/app/views/books/edit.html.erb
<div class="body">
  <div class="container">
  <p id="notice"></p>
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1>Editing Book</h1>

      <%= form_for @book do |f| %>
      <% if @book.errors.any? %>
        <div id="error_explanation">
        <h2><%= @book.errors.count %> error prohibited this book from being saved:</h2>
        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
        </div>
      <% end %>

          <div class="field">
            <%= f.label :Title,%>
            <%= f.text_field :title, id: :book_title, class="col-xs-12"%>
          </div>

          <div class="field">
            <%= f.label :Opinion %>
            <%= f.text_area :body, id: :book_body, class="col-xs-12"%>
          </div>

          <div class="actions">
            <%= f.submit 'Update Book', class: "btn btn-primary col-xs-12"%>
          </div>
          <% end %>

          <%= link_to 'Edit', edit_book_path(@book) %> |
          <%= link_to 'Back', books_path %>
    </div>
    </div>
  </div>
</div>

vagrant/apptest2/app/views/books/index.html.erb
<div class="container">
              <p id="notice">Welcome! You have signed up successfully.<%= notice %></p>
              <div class="row">
                      <div class="col-xs-3">
                             <h2>User info</h2>
                                 <table class ="table">
                                          <tr>
                                          <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" , size:'100x100'%>
                                          </tr>
                                          <tr>
                                              <th>name</th>
                                              <th><%= @teruya.name%></th>
                                           </tr>
                                           <tr>
                                              <th>introduction</th>
                                              <th><%= @teruya.introduction %></th>
                                           </tr>
                                 </table>
                                   <a class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_path" href="/users/id/edit"></a>
                                  <h2>New book</h2>
                                    <%= form_for(@book) do |f| %>
                                                  <% if @book.errors.any? %>
                                                                    <div id="error_explanation">
                                                                            <h2><%= @book.errors.count %> error prohibited this book from being saved:</h2>

                                                                                  <ul>
                                                                                    <% @book.errors.full_messages.each do |message| %>
                                                                                      <li><%= message %></li>
                                                                                    <% end %>
                                                                                  </ul>
                                                                    </div>
                                                  <% end %>
                                <div class="field row">
                                         <%= f.label :Title%>
                                         <%= f.text_field :title %>
                                </div>
                                <div class="field row">
                                        <%= f.label :Opinion%>
                                        <%= f.text_area :body %>
                                </div>
                                <div class="actions">
                                        <%= f.submit "Create Book", class: "btn btn-primary col-xs-12"%>
                                </div>
                                <% end %>
                    </div>
　　　　             <div class="col-xs-9">
　　　　                     <h2>Books</h2>
                            <table class="table ">
　　　　                           <thead>
                                            <tr>
                                              <th></th>
                                              <th>Title</th>
                                              <th>Opinion</th>
                                              <th colspan="3"></th>
                                            </tr>
                                  </thead>

                                  <tbody>
                                      <% @book_path.each do |book| %>
                                              <tr>
                                                  <td>
                                                      <a href="/users/:id">
                                                      <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpeg" , size:'50x50'%>
                                                      </a>
                                                  </td>
                                                  <td>
                                                       <%= link_to book_path(book.id) do %>
                                                       <%= book.title %>
                                                       <% end %>
                                                       </a>
                                                  </td>
                                                  <td><%= book.body %></td>
                                              </tr>
                                      <% end %>
                                  </tbody>
                          </table>
                    </div>
              </div>
</div>

vagrant/apptest2/app/views/books/new.html.erb
    <h2>New book</h2>
      <%= form_for(@book) do |f| %>
        <% if @book.errors.any? %>
           <div id="error_explanation">
           <h2><%= @book.errors.count %> error prohibited this book from being saved:</h2>

            <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="field row">
          <%= f.label :Title %>
          <%= f.text_field :title %>
        </div>
        <div class="field row">
          <%= f.label :Opinion %>
          <%= f.text_area :body %>
        </div>
        <div class="actions">
          <%= f.submit "Create Book", class: "btn btn-primary col-xs-12" do%>
        </div>
      <% end %>

vagrant/apptest2/app/views/books/show.html.erb
<div class="container">
    <p id="notice">Welcome! You have signed up successfully.<%= notice %></p>
    <div class="row">
            <div class="col-xs-3">
                <h2>User info</h2>
                <table class ="table">
                     <tr>
                         <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" , size:'100x100'%>
                     </tr>
                     <tr>
                         <th>name</th>
                         <th><%= @teruya.name %></th>
                     </tr>
                     <tr>
                         <th>introduction</th>
                         <th><%= @teruya.introduction %></th>
                     </tr>
                </table>
                     <a class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_path" href="/users/id/edit"></a>

                <h2>New book</h2>
                     <%= form_for(@book) do |f| %>
                        <% if @book.errors.any? %>
                             <div id="error_explanation">
                                   <h2><%= @book.errors.count %> error prohibited this book from being saved:</h2>
                                   <ul>
                                        <% @book.errors.full_messages.each do |message| %>
                                            <li><%= message %></li>
                                        <% end %>
                                    </ul>
                             </div>
                        <% end %>
                          <div class="field row">
                             <%= f.label :Title %>
                             <%= f.text_field :title %>
                          </div>
                          <div class="field row">
                             <%= f.label :Opinion %>
                             <%= f.text_area :body %>
                          </div>
                          <div class="actions">
                             <%= f.submit "Create Book", class: "btn btn-primary col-xs-12"%>
                          </div>
                     <% end %>
            </div>


                <div class="col-xs-9">
                     <h2>Book detail</h2>
                              <table class="table">
                                  <tbody>
                                     <% @book_path.each do |book| %>
                                       <tr>
                                            <th>
                                                 <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" , size:'50×50'%>
                                            </th>
                                            <td>
                                                <%= @teruya.name%>
                                            </td>
                                            <td><%= link_to user_path(user.id) do%>
                                                <%= @shota.title %>
                                            <%end%>
                                             </td>
                                            <td><%= @shota.body %></td>
                                            <td><%= link_to 'Edit', edit_book_path(book), class: "btn-sm btn-success" %></td>
                                            <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: '本当に消しますか?' }, class: "btn-sm btn-danger" %></td>
                                       </tr>
                                     <% end %>
                                  </tbody>
                              </table>
                </div>
      </div>
</div>

vagrant/apptest2/app/views/home/about.html.erb
<div class="body">
<div class="container">
  <div class="row">
  <div class="top-message col-md-offset-3 col-md-6">
　　<h1>Welcome to <span class="glyphicon glyphicon-book"></span>
	<strong>Bookers</strong>!</h1>
  </div>
  </div>
</div>
</div>

vagrant/apptest2/app/views/home/index.html.erb
<div class="body">
<div class="container">
    <div class="row">
      <div class="top-message col-md-offset-3 col-md-6">
        <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
        <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>

  <div class="btn-wrapper">
    <div class="row">
      <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
    </div>
    <div class="row">
      <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
    </div>
  </div>
</div>
</div>

vagrant/apptest2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

      <header class="navbar  navbar-inverse">
        <div class="container">
        <nav class="navbar-left">
          <span>Bookers</span>
        </nav>
        </div>
        <nav>
        <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to user_path(current_user.id), class: "my-bt" do%><i class="glyphicon glyphicon-home"></i>Home<% end %></li>
             <li><%= link_to users_path, class: "my-bt" do%><i class="glyphicon glyphicon-user"></i>Users<% end %></li>
             <li><%= link_to books_path, class: "my-bt" do%><i class="glyphicon glyphicon-book"></i>Books<% end %></li>
              <li><%= link_to destroy_user_session_path, method: :delete, class: "my-bt" do%><i class="glyphicon glyphicon-log-in"></i>logout<% end %></li>

            <% else %>
             <li><%= link_to root_path, class: "my-bt" do%><i class="glyphicon glyphicon-home"></i>Home<% end %></li>
            <li><%= link_to home_about_path, class: "my-bt" do%><i class="glyphicon glyphicon-link"></i>About<% end %></li>
            <li><%= link_to new_user_registration_path, class: "my-bt" do%><i class="glyphicon glyphicon-edit"></i>sign up<% end %></li>
            <li><%= link_to new_user_session_path, class: "my-bt" do%><i class="glyphicon glyphicon-log-in"></i>login<% end %></li>
            <% end %>
          </ul>
        </nav>
        </div>
      </header>
     <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>

    <footer>
        <div class="container">
        <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
        <p>CopyRight Infratop.inc</p>
      </div>
    </div>
  </div>
</footer>

  </body>
</html>

vagrant/apptest2/app/views/users/edit.html.erb
<div class="body">
  <div class="container">
  <p id="notice"></p>
  <h2>User info</h2>
  <%= form_for (@user) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= @user.errors.count %> error prohibited this object from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :name, id: :user_name %>
  </div>

  <div class="field">
    <%= f.label :Image %><br>
    <%= f.attacment_field :profile_image, id: :user_profile_image %>
  <div>

  <div class="field">
    <%= f.label :Intoroduction %><br>
    <%= f.text_field :introduction, id: :user_introduction  %>
  </div>

  <div class="actions">
    <%= f.submit "Update User" %>
  </div>
  <% end %>
  </div>
</div>

vagrant/apptest2/app/views/users/index.html.erb
<div class="container">
    <p id="notice">Welcome! You have signed up successfully.<%= notice %></p>
    <div class="row">
            <div class="col-xs-3">
                <h2>User info</h2>
                <table class ="table">
                     <tr>
                         <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" , size:'100x100'%>
                     </tr>
                     <tr>
                         <th>name</th>
                         <th><%= @teruya.name %></th>
                     </tr>
                     <tr>
                         <th>introduction</th>
                         <th><%= @teruya.introduction %></th>
                     </tr>
                </table>
                     <a class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_path" href="/users/id/edit"></a>
                <h2>New book</h2>
                     <%= form_for(@book) do |f| %>
                        <% if @book.errors.any? %>
                             <div id="error_explanation">
                                   <h2><%= @book.errors.count %> error prohibited this book from being saved:</h2>
                                   <ul>
                                        <% @book.errors.full_messages.each do |message| %>
                                            <li><%= message %></li>
                                        <% end %>
                                    </ul>
                             </div>
                        <% end %>
                          <div class="field row">
                             <%= f.label :Title %>
                             <%= f.text_field :title %>
                          </div>
                          <div class="field row">
                             <%= f.label :Opinion %>
                             <%= f.text_area :body %>
                          </div>
                          <div class="actions">
                             <%= f.submit "Create Book", class: "btn btn-primary col-xs-12"%>
                          </div>
                     <% end %>
            </div>

            <div class="col-xs-9">
               <h2>Users</h2>
                    <table class="table">
                        <thead>
                           <tr>
                              <th>Image</th>
                              <th>name</th>
                              <th colspan="3"></th>
                           </tr>
                        </thead>

                        <tbody>
                          <% @user_path.each do |user| %>
                           <tr>
                              <td> <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpeg" , size:'50x50'%></td>
                              <td><%= user.name %></td>
                              <td><%= user.introduction %></td>
                              <td><%= link_to 'Show',"/users/#{user.id}"%></td>
                            </tr>
                          <% end %>
                        </tbody>
                    </table>
            </div>
  </div>
</div>

vagrant/apptest2/app/views/users/show.html.erb
<div class="container">
    <p id="notice">Welcome! You have signed up successfully.<%= notice %></p>
      <div class="row">
          <div class="col-xs-3">
          <h2>User info</h2>
              <table class ="table">
                  <tr>
                  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" , size:'100x100'%>
                  </tr>
                  <tr>
                      <th>name</th>
                      <th><%= @teruya.name %></th>
                  </tr>
                  <tr>
                      <th>introduction</th>
                      <th><%= @teruya.introduction %></th>
                  </tr>
              </table>

              <div class='row'>
              <a class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_path" href="/users/id/edit"></a>
              </div>

                <h2>New book</h2>
                <%= form_for(@book) do |f| %>
                    <% if @book.errors.any? %>
                        <div id="error_explanation">
                        <h2><%= @book.errors.count %> error prohibited this book from being saved:</h2>

                          <ul>
                          <% @book.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                            <% end %>
                          </ul>
                        </div>
                    <% end %>
                        <div class="field row">
                            <%= f.label :Title %>
                            <%= f.text_field :title %>
                        </div>
                        <div class="field row">
                            <%= f.label :Opinion %>
                            <%= f.text_area :body %>
                        </div>
                        <div class="actions">
                            <%= f.submit "Create Book", class: "btn btn-primary col-xs-12" do%>
                        </div>
                <% end %>
          </div>

          <div class="col-xs-9">
                <h2>Books</h2>
                <table class="table table-hover table-inverse">
                    <thead>
                        <tr>
                            <th></th>
                            <th>Title</th>
                            <th>Opinion</th>
                            <th colspan="3"></th>
                        </tr>
                    </thead>

                    <tbody>
                    <% @books.each do |book| %>
                        <tr>
                            <td>
                            <a href="/users/:id">
                            <%= attachment_image_tag @user, :profile_image, :fill, 50, 50, format: 'jpeg', fallback: "no_image.jpg" , size:'50×50'%>
                            </a></td>
                            <td>
                            <a href="/books/:id">
                            <%= book.title %>
                            </td>
                            <td><%= book.body %></td>
                            </tr>
                  <% end %>
                  </tbody>
              </table>
        </div>
     </div>
</div>